CREATE OR REPLACE TRIGGER BRG_VBMG_KLA_ACMP_1
BEFORE UPDATE OR INSERT 
ON VBMG_KLANTEN
FOR EACH ROW
BEGIN
	IF (NOT (:new.NAAM = 'g'))
	THEN
	RAISE_APPLICATION_ERROR (-20001,'BRG_VBMG_KLA_ACMP_1 was triggered');
	END IF;
END BRG_VBMG_KLA_ACMP_1;
